# Generated by Django 4.0 on 2022-01-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('counted_views', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('creted_date', models.DateField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
